import { ContextEntry, ModuleState } from "./types";

export function generatePrompt(entries: ContextEntry[]): string {
  if (entries.length === 0) return "No context found for this branch.";

  const latest = entries[entries.length - 1];
  const timeAgo = getTimeAgo(latest.timestamp);

  let prompt = `## Project Context (auto-generated by DevContext)\n\n`;
  prompt += `**Repo:** ${latest.repo}\n`;
  prompt += `**Branch:** ${latest.branch}\n`;
  prompt += `**Last session:** ${timeAgo}\n`;
  prompt += `**Author:** ${latest.author}\n\n`;

  prompt += `### Current Task\n${latest.task}\n\n`;

  if (latest.goal) {
    prompt += `### Goal\n${latest.goal}\n\n`;
  }

  if (latest.approaches.length > 0) {
    prompt += `### What's Been Tried\n`;
    latest.approaches.forEach((a) => (prompt += `- ${a}\n`));
    prompt += `\n`;
  }

  if (latest.decisions.length > 0) {
    prompt += `### Key Decisions\n`;
    latest.decisions.forEach((d) => (prompt += `- ${d}\n`));
    prompt += `\n`;
  }

  prompt += `### Current State\n${latest.currentState}\n\n`;

  if (latest.nextSteps.length > 0) {
    prompt += `### Next Steps\n`;
    latest.nextSteps.forEach((s, i) => (prompt += `${i + 1}. ${s}\n`));
    prompt += `\n`;
  }

  if (latest.blockers && latest.blockers.length > 0) {
    prompt += `### Blockers\n`;
    latest.blockers.forEach((b) => (prompt += `- ⚠️ ${b}\n`));
    prompt += `\n`;
  }

  if (latest.filesChanged.length > 0) {
    prompt += `### Files Changed Recently\n`;
    latest.filesChanged.forEach((f) => (prompt += `- ${f}\n`));
    prompt += `\n`;
  }

  if (latest.recentCommits.length > 0) {
    prompt += `### Recent Commits\n`;
    latest.recentCommits.forEach((c) => (prompt += `- ${c}\n`));
    prompt += `\n`;
  }

  // Add history summary if multiple sessions
  if (entries.length > 1) {
    prompt += `### Session History (${entries.length} sessions)\n`;
    entries
      .slice(-5)
      .reverse()
      .forEach((e) => {
        prompt += `- [${new Date(e.timestamp).toLocaleString()}] ${e.task}\n`;
      });
    prompt += `\n`;
  }

  if (latest.handoffNote) {
    prompt += `### Handoff Note\n${latest.handoffNote}\n\n`;
  }

  return prompt;
}

export interface ModulePromptOptions {
  branch: string;
  repo?: string;
  currentPathHint?: string;
  maxModules?: number;
}

export function generateModulePrompt(
  states: ModuleState[],
  options: ModulePromptOptions
): string {
  if (states.length === 0) return "No module state found for this branch.";

  const maxModules = options.maxModules || 5;
  const ranked = rankStatesByRelevance(states, options.currentPathHint)
    .filter((s) => s.confidence >= 0.5)
    .slice(0, maxModules);

  // Safety fallback: if all states are low confidence, still provide the most recent few.
  const selected = ranked.length > 0 ? ranked : rankStatesByRelevance(states, options.currentPathHint).slice(0, 3);

  const latestUpdate = selected
    .map((s) => new Date(s.lastUpdated).getTime())
    .sort((a, b) => b - a)[0];
  const latestTimeText = latestUpdate ? getTimeAgo(new Date(latestUpdate).toISOString()) : "unknown";

  let prompt = `## Project Context (module-aware, auto-generated by DevContext)\n\n`;
  prompt += `**Repo:** ${options.repo || selected[0].repo}\n`;
  prompt += `**Branch:** ${options.branch}\n`;
  prompt += `**Focus modules:** ${selected.length}\n`;
  prompt += `**Last update:** ${latestTimeText}\n\n`;

  prompt += `### Priority Focus\n`;
  selected.forEach((state, index) => {
    prompt += `${index + 1}. ${state.module} (confidence: ${state.confidence.toFixed(2)})\n`;
    prompt += `   - Task: ${state.currentTask || "No active task inferred yet"}\n`;
    prompt += `   - State: ${state.currentState || "No state summary captured yet"}\n`;
    if (state.nextSteps.length > 0) {
      prompt += `   - Next: ${state.nextSteps.slice(0, 2).join(" | ")}\n`;
    }
    if (state.decisions.length > 0) {
      prompt += `   - Decisions: ${state.decisions.slice(-2).join(" | ")}\n`;
    }
    if (state.failedAttempts.length > 0) {
      prompt += `   - Avoid: ${state.failedAttempts.slice(-2).join(" | ")}\n`;
    }
  });
  prompt += `\n`;

  const touchedFiles = flattenUnique(selected.flatMap((s) => s.touchedFiles)).slice(-12);
  if (touchedFiles.length > 0) {
    prompt += `### Recently Touched Files\n`;
    touchedFiles.forEach((file) => {
      prompt += `- ${file}\n`;
    });
    prompt += `\n`;
  }

  prompt += `### Hand-off Instruction For AI\n`;
  prompt += `Continue from the priority focus above. Preserve existing decisions unless contradicted by tests or requirements.\n`;

  return prompt;
}

function rankStatesByRelevance(states: ModuleState[], currentPathHint?: string): ModuleState[] {
  const hint = (currentPathHint || "").replace(/\\\\/g, "/").replace(/^\/+/, "").toLowerCase();

  return [...states].sort((a, b) => scoreState(b, hint) - scoreState(a, hint));
}

function scoreState(state: ModuleState, hint: string): number {
  const now = Date.now();
  const updatedAt = new Date(state.lastUpdated).getTime();
  const ageHours = Number.isFinite(updatedAt) ? Math.max(0, (now - updatedAt) / (1000 * 60 * 60)) : 999;

  let score = state.confidence * 100;

  // Recency contribution.
  if (ageHours < 2) score += 30;
  else if (ageHours < 24) score += 18;
  else if (ageHours < 72) score += 8;

  // Path relevance contribution.
  if (hint) {
    const moduleKey = state.module.toLowerCase();
    if (hint.includes(moduleKey) || moduleKey.includes(hint)) {
      score += 35;
    } else {
      const fileHit = state.touchedFiles.some((f) => {
        const normalized = f.replace(/\\\\/g, "/").toLowerCase();
        return normalized.includes(hint) || hint.includes(normalized);
      });
      if (fileHit) score += 20;
    }
  }

  return score;
}

function flattenUnique(values: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  values.forEach((v) => {
    if (!seen.has(v)) {
      seen.add(v);
      out.push(v);
    }
  });
  return out;
}

function getTimeAgo(timestamp: string): string {
  const diff = Date.now() - new Date(timestamp).getTime();
  const minutes = Math.floor(diff / 60000);
  if (minutes < 60) return `${minutes} minutes ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} hours ago`;
  const days = Math.floor(hours / 24);
  return `${days} days ago`;
}
